### PR TITLE
Push livestream manual

### PR DESCRIPTION
**Pull request by JulienPeloton**
**IMPORTANT: Please create an issue first before opening a Pull Request.**
Linked to issue(s): #66

## What changes were proposed in this pull request?

This PR brings a manual to install and use the livestream service of Fink

## How was this patch tested?

Manually

### CODE REVIEW

**Comment by JulienPeloton** [comment]
@emilleishida @anaismoller is the text OK to be merged?

**Comment by JulienPeloton** [comment]
Thanks @anaismoller, I've incorporated your suggestions in the manual.

**Comment by emilleishida** [comment]
in the end of the stream manual, when it is said:

`You should start to see alert flowing!`

what exactly do you mean?

I see something like:

`2021-03-05 11:00:40.000319|fink_early_sn_candidates_ztf|ZTF21aalcsng   |0|0.687     |0.8705604076385498`

only this line. Is this what is expected? 
If so I would include an example output and some explanation of what it is showing so people can know things are ok. 

if I understood correctly the idea of the script is to use the output of the `poll_single_alert` to use it for something, like a data frame or something else. If so, this should be said as well (1 phrase is enough).

**Comment by emilleishida** [comment]
in the concrete example of a filter, output of the function will be a series of boolean, is this what is expected?
If so, it would be important to say what is the expected output, or if such requirements do not exist

**Comment by JulienPeloton** [comment]
> in the end of the stream manual, when it is said:
> 
> `You should start to see alert flowing!`
> 
> what exactly do you mean?
> 
> I see something like:
> 
> `2021-03-05 11:00:40.000319|fink_early_sn_candidates_ztf|ZTF21aalcsng |0|0.687 |0.8705604076385498`
> 
> only this line. Is this what is expected?
> If so I would include an example output and some explanation of what it is showing so people can know things are ok.
> 
> if I understood correctly the idea of the script is to use the output of the `poll_single_alert` to use it for something, like a data frame or something else. The way it is right now it is printed but not stored anywhere, so it will not be used for other purposes.
> 
> If so, this should be said as well (1 phrase is enough).

Thanks! I have rephrased the manual. In short, yes the printout is expected from this example. Of course, this is the simplest example, and users are encouraged to do more! (pandasify, save on disk, add filters, etc..)

**Review by anaismoller — COMMENTED** [review]
looks good

**Comment by JulienPeloton** [comment]
Thanks @emilleishida @anaismoller for the review -- I'm merging the branch

**Pull request merged**
