### PR TITLE
Update installation instructions with pip usage

### PR DESCRIPTION
**Pull request by aboucaud**
## What changes were proposed in this pull request?

How is the issue this PR is referenced against solved with this PR?

## How was this patch tested?

### CODE REVIEW

**Comment by JulienPeloton** [comment]
Thanks @aboucaud, this is indeed nicer to install locally from pip and avoid the update to the bash_profile 👍 

PR looks to me - let me know if I can merge or if there is more you want to push.

**Comment by aboucaud** [comment]
Sorry, pull request was sent before I finished editing it.

I tried to see if we could get rid of the environment variable at all. That would be even better since it does not leave a hardcoded path in the `.bashrc`. 

Do you have an opinion ?

**Comment by JulienPeloton** [comment]
No, I would keep it for the moment since it is a rather common operation. 

However I agree in the short-term it should disappear, by e.g. using a proper `pip install fink-client` from pypi. But I need first to resolve the handling of the configuration file (i.e. for the moment the user needs to edit `fink_client/fink_client_conf.py` manually...).

**Comment by aboucaud** [comment]
Then it's good to merge !

**Comment by JulienPeloton** [comment]
Thanks, this is a great added value! Merging then.

Note I opened an issue (#50) to get a proper installation via pip. This should be available in the next release.

**Comment by aboucaud** [comment]
Do you want me to do the same for the other packages or are you handling it ?

**Comment by JulienPeloton** [comment]
Thanks for proposing your help! I do not think this is required for other packages as they are not supposed to be exposed to users (like fink-broker which is based on Spark), or currently suffer the same problem of configuration file (like fink-alert-simulator), or they are already _pip installable_ (like fink-filters, fink-science).

However, once I implement #50 , it would be super if you can be a beta tester!

**Comment by aboucaud** [comment]
Sure can do !

**Comment by JulienPeloton** [comment]
Thanks!

**Pull request merged**
